language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: C1yj0lrNXHvbmiyeryC6GDatD+vWXlj6zmdPIC490wxJZb/fKcRS/uwtajpYi7eMPR2zQxhmw6W3eInfGfyrqM7ch3oUgqk0hfZ3B2rKcOiZ+vA9uDGh/Lkm9sdu4M2t9+7tiX/yBrKx9dgn1JznVGkYn2vQYP/QmrlJLlLqmMS5/0/ViUU6Ja0arbEg/9VkGzVrbu6Z5XdudzyS/vO/AciBki1rWhkZpnjKeZio0J9SYP/K7HVfD81q9+/l7dfkR7Ct35SLYspPe/27L1U3QW+ehqqtMts8TMeVoP/vxzP6srD2f0e3qwzDFdYqARmdVreSz9uwVmoxBT8e6/RLf1q97tPNa3SJPSl5HzrV3VHQrHrDd+GT+8nQbQl31GJyXfkRIRioHmAVUikK/D0iWal6KVAhUIt6o5xL5RcFoLp/BwV2q2ElCYFeZzT/S4DJQOvm3JT3Z7LVLKyRMFpOzMvmB7eqWjUp+trfDH+KrtvpI7BiRiA7bcgpkeNk742sx2DuIm8kKQdQyJnNsRAOokBjLZ8L/6ERi2jTrdNib094Zcxd7D9LEHD4s6rHZbzyv9befCp+dA+YGr+OQWMgYXfBESReff8/NSA7bf9WPPsYhv7dMkjRG028dc5IfBUaLo3jk4EINYEhjpeXNGp3oXBddKxle2A5UQIc8bnO2xg=
  app: project-b-08
  on:
    repo: uva-cs3240-s21/project-b-08
