language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: idIxdWBT3K666YkyE66i80x3y3Tq1CqCZnwfoMmZ6W7wpNk3tyUl5vEWdpGs4LWjOUZMRjnrHKQX5v6ez9Tc3z6v4g/8K5MkFjbifeRElS/FEh0WWxBXEjB5ys2RUTLh0KcPXlivXYrBS12r19XbaUhMSE1DnQCrW4oPrrNGnxR0kQjbsvUlwrjxAZNgV/pPkROdibbGXWjwRFFoBu77A05X5u6g0GKXHKsDrqdJoFhMw19JAnG2nCVlR55PMhag9vvjqnWd9DSteDMEDenRhNrBxehprWBsUldJAETb6iZXloD1hFiNWddnvng3UuEOymqkIYuHj2DrAvc3+y7LR+nVddA7EYhGZf8YmcxU355M6PPTFChy30mceWSePKGsHNKjs2BAMm+W5+99bQc361Q4UT3UN4O7wsL2UDFwBxuiEuovJ+XeA9eiw0Gqjb2uUwJnGkuMSX0hyltyiEPJ2f7kcpx4eXIKZmJcSCJzrj4OZwOqVg7kFg8D4YY1u7fRcxlLKRKUKvrKeddaxzuPaiJ/Phcu2ibeuQv0vOJvpn1ONRtpVvuy6JvQWGttbmvOhjS8gHg+06jlhG3fuglOrao6d5MWT9wjysSbLyzyzE13Kzf58Tz7I2mmlFjKj8ZVkOY1GKll1Tj/EgXBYtyEqhe+IpPhepGTI1LnW6d2QGA=
  app: project-b-08
  on:
    repo: uva-cs3240-s21/project-b-08
