language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: v3M9pX9FDmGsbeNwQQola+wjwzq94v5TJEgDYHpJYmsouNREaMnzwDj7R6B2ftXToSSKnudCvn4jCH/hNtgXz9ejS44aAYeBLQHeL3MjCMsTSgm9CNvmO2Tpbq5S7usE5WHjoNMau4YscBQ8JpONi770T0h8gHi1TzN/4l4/EX5YADO7xZUz/6gWWohmn5148v3c9RnQtmfWO/GWVTgR6C3WjPzYPcKtZozOYlhI6x871lFAkoDsxdQ2Sl/isuOrl1256lEz1vEO03pqEb/txv67eAaVideA/mM5B4apMC57vv5kDZpYL/2R1K8kn/w7RQQ21Vfal6J2daYM0VBvZuwZ9adinvhpVbyG/OhV+FEbxDSSfC4Et0s/NIr3VtzJ6+kf/D9jHix0NdWouvEEZjIJzNsSUex6JuJ62z9XVmfrlR4HaL/1u12GOLMk5TchhpBv29A03QOVmyTrouWOPYv7Dk64ocnc3G+M91pLl+zYz9MJO8yj8d5ERiwBS+OVbx1TCqP6LmiB4K8hTsgLrf0gpwYP0hpYIRJEKc6GWDrRwwm0B8eNK3DbG90OCb+9yHlY+Dlb+ZUeLehF/TEynp+eTI1/s5M7MZyu/8XndNWjRYd2Irjob4jkQlaCzR1npl4O7JVAVUgtbIapG9y7K01Y+sf8DutqhaQGQRVB3ew=
  app: project-b-08
  on:
    repo: uva-cs3240-s21/project-b-08
