language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: Mf8iboeVL+Zw1RhLOegR2YjY9zpXVyxB02ct7qf3uCfm2Aq+B+TiNuAq3PBOwEdUAN4Q0x2YIhjdV1d9o4JEYU817sQSoY9MQVHx+4lFZ+Q73pRfGLrs+z0rlZi1pLbPpfAtahgGV/u+S3xuhaBApONHlu3QvVM5d6pldb9Xb1MGJ+M19S6aU1ayXVtxu605fpu96mqoRZP4aHgR+68LtoVwKKNDCWxRYF13646uTFBCdho5+7rCeZhhRQDrF5lqbbIF+ie3WUHqf4MG8JXasnXKTdMwGpf4b53aUao/3v28XQliUx6NudGEyHaOQFSROcrSXKlFFpeq1ae4RkKgl8I6qh/ZEa/ZYaJ2Cee39vaG/bZ8I+nDm5kJwdgDh8LbSJy7YtJ02HOEEW8HBYqaJjvNQx8MktBbUjNTYvJbLXMRCJ0uMAgbGVa2RaUwu+StmMke1JvZDFWiOh0zMzPGRJ0R54FiVYBheBsq33Ux3f2F8hQMXuWaBYrk+4aBpjEE3Nv4eE5pd3kezDS+bOTol642ocdYVxzyQ9aDUQ3Yl7fcyLR8QVT9Z51uIyT5vRCJqvTB+l7NA1q1r7oldF/UxNwjsYT8udAoHYy1Vz7J5Ck9XWBmYi3jf0c0Tdq8Z5BYzS8mSxOx+LXOnvyWDnIszyuyO5+/h6o1PEiA4TaeZ60=
  app: project-b-08
  on:
    repo: uva-cs3240-s21/project-b-08
