language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: CCoHfa5Sq1RtpodFR3PlNM8dAeWMKNWQsMFNYrim2ZWBaUYRHIs4xXzqQ/aSvTCcn7jysh4wEJILvdQAffmoLBLg6fOEFFchFE30BedIKeNhuj8BaSWjKLN+YWAMVmmBXQAvUMHdRX65ccKhisZB3ybsUogWH4hpNt8d62GT5sKCG/gU5ky0L6QE4u8S0o9btgKvuQutdErFFXX98tSeKaKM6lx2v7PphBCLQNXuLun+tV2watGo2+fsXd3F2gF3kNlsPhYhRGiVmunjRLMLXykRHuAi5atEwVZhYzRh1A/yExly3v7SJM1pIwd0Zn4lUo/oN1lna/AZxnO7/vsZSlUbrW2hjr3ncXHVqc9DMC4lQQtipfTXuJp7YaODeKDSaRBzOd/PN9XiTZAwbPbaVZsctr/3LuLskTyyAV5M5xEGKAl8t1qchssppgQGc8B2wOjMsY64uqdl44mUEm0ucbWQZIAg4+IAukuxdYSrZv/+jbsH1cXPhT0e7OGkCWFh/bfJPxIioUdHfcNcxIzwWDjWyxHxKBrP8ac36L/tuy98qTfXG6GZTyYApmqhpLyJFNfJv54np38TXQxUtx1rMpoEEqeN51GlsjxZk48E1QvXdcN4H0WO+rRQGaR6+3h7r9SHqJL+8EKF9QxjzRIXXXMKiAJSleDr3X+bWCFUH1c=
  app: project-b-08
  on:
    repo: uva-cs3240-s21/project-b-08
