language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: Ichgxt6tbnFBaMuxCaJgCFrssSJl6Ew2TFEy6/06UDaxsUjiAeddZWAFmrcETvar7sFTDIuez5tMH/uI9YFc6F6DdLpiqCd2rnZseYQ9iaG9x2+5in7Yra9rH4OC5tTNwBqhtBerGDtnpJGABxwhJR6IeiupD80dsFIaMrAtvDaO24EtabpKagWSOUNno5cOBJBqve4Vxq5sAH6+EGQbw3MP/XpmP5SOXdNhHSmj1bpCE+mb2TCrae7YK74Trs9SMQn9cqF+BhJey5fiUexkSqg8suaxZSEFyTSTes5JOpm7p+rEG5hj6Za+bWIPtRnJu9oOxW1IDUD8t2QbX2WaLslwgXvod0FI6Sj4erKvK8eIYfSh0w0ZWpPgiFd3yurrYMz4Ei0rs00rwyW48z7XpCpRagTeZMbKTn5cFcWjzw6a1GTDyS4sHGS+/0iu/jBmq+V2v6IxVT1ah7Jr11Dr4B4YYMe7pupF2WgJMqAvKcDMY35+69XB6UCQ0Ed6D0CTfHoixBPfzHaCevAAB+1y5PcmmpGPdK363bdU+GJQH0hq+DY8/TFU6QXk1uyqxiYKnVokaMfH6z1kyzUnfdp6y1GOKonNLBhnS2dVvf+TnlsFXjclGy5kBc8qScGm2xalW125Z0mhUy8veeLiAdmAGeGQuBR2nn2X6bWs/qi5veE=
  app: project-b-08
  on:
    repo: uva-cs3240-s21/project-b-08
